// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import AppstoreOutlined from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/portal/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import ClusterOutlined from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/portal/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ClusterOutlined';
import RadarChartOutlined from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/portal/web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RadarChartOutlined';
export default { AppstoreOutlined, ClusterOutlined, RadarChartOutlined };
