// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import TeamOutlined from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import UserOutlined from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import RadarChartOutlined from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RadarChartOutlined';
export default { TeamOutlined, UserOutlined, RadarChartOutlined };
