// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import TeamOutlined from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/portal/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import AppstoreOutlined from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/portal/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import RadarChartOutlined from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/portal/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RadarChartOutlined';
export default { TeamOutlined, AppstoreOutlined, RadarChartOutlined };
