// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/account","name":"账号管理","icon":"UserOutlined","parentId":"ant-design-pro-layout","id":"2"},"3":{"path":"/account/tenant","name":"租户管理","parentId":"2","id":"3"},"4":{"path":"/account/user","name":"系统用户","parentId":"2","id":"4"},"5":{"path":"/account","redirect":"/account/tenant","parentId":"2","id":"5"},"6":{"path":"/production","name":"生产管理","icon":"RadarChartOutlined","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/production/type","name":"型号规格","parentId":"6","id":"7"},"8":{"path":"/production/batch","name":"生产批次","parentId":"6","id":"8"},"9":{"path":"/production/product","name":"产品列表","parentId":"6","id":"9"},"10":{"path":"/production","redirect":"/production/type","parentId":"6","id":"10"},"11":{"path":"/maintainance","name":"维护管理","icon":"ToolOutlined","parentId":"ant-design-pro-layout","id":"11"},"12":{"path":"/maintainance/firmware","name":"固件升级","parentId":"11","id":"12"},"13":{"path":"/maintainance/sim-card","name":"SIM卡管理","parentId":"11","id":"13"},"14":{"path":"/maintainance/task","name":"任务管理","parentId":"11","id":"14"},"15":{"path":"/maintainance","redirect":"/maintainance/firmware","parentId":"11","id":"15"},"16":{"path":"/","redirect":"/login","parentId":"ant-design-pro-layout","id":"16"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Tenant__index" */'@/pages/Tenant/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Account__index" */'@/pages/Account/index.tsx')),
'5': React.lazy(() => import('./EmptyRoute')),
'6': React.lazy(() => import('./EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Sensor__Type__index" */'@/pages/Sensor/Type/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Sensor__Batch__index" */'@/pages/Sensor/Batch/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Sensor__Product__index" */'@/pages/Sensor/Product/index.tsx')),
'10': React.lazy(() => import('./EmptyRoute')),
'11': React.lazy(() => import('./EmptyRoute')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Sensor__Firmware__index" */'@/pages/Sensor/Firmware/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__SImCard__index" */'@/pages/SImCard/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__Sensor__Task__index" */'@/pages/Sensor/Task/index.tsx')),
'15': React.lazy(() => import('./EmptyRoute')),
'16': React.lazy(() => import('./EmptyRoute')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/tju/Langhu/Products/Sentinel/Codes/Platform/client/admin/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
