"""
Database connections and utilities
Handles MySQL, Redis, InfluxDB, and MinIO connections

Uses config injection: call init() with URL/credentials instead of
reading from a hard-coded app.config module. This makes the module
reusable across api and dia services.
"""

import logging
from typing import AsyncGenerator, Optional

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker
from sqlalchemy.pool import NullPool
import redis
from influxdb_client import InfluxDBClient
from minio import Minio
from minio.error import S3Error

from pub.models import Base, import_all_models

logger = logging.getLogger(__name__)


# ===== MySQL Database =====
class DatabaseManager:
    """Manager for MySQL database connections"""

    def __init__(self):
        self.engine = None
        self.SessionLocal = None
        self._mysql_url: str = ""
        self._debug: bool = False
        self._schema_ready: bool = False

    async def init(self, mysql_url: str, debug: bool = False) -> None:
        """Initialize database engine and session factory.

        Args:
            mysql_url:  SQLAlchemy async engine URL (e.g. mysql+aiomysql://user:pass@host:port/db)
            debug:      Enable SQL echoing when True.
        """
        try:
            self._mysql_url = mysql_url
            self._debug = debug
            self.engine = create_async_engine(
                mysql_url,
                # echo=debug,
                echo=False,  # 通过 logging 配置控制日志输出，避免 SQL 语句过多时日志过于冗长
                poolclass=NullPool,
                pool_pre_ping=True,
            )
            self.SessionLocal = async_sessionmaker(
                self.engine, class_=AsyncSession, expire_on_commit=False
            )
            self._schema_ready = False
            await self.ensure_schema()
            # logger.info("MySQL database initialized successfully")
        except Exception as e:
            logger.error(f"Failed to initialize MySQL database: {e}")
            raise

    async def ensure_schema(self) -> None:
        """Create missing tables for registered SQLAlchemy models."""
        if self.engine is None:
            raise RuntimeError("Database engine not initialized. Call init() first.")
        if self._schema_ready:
            return
        import_all_models()
        async with self.engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
            await self._ensure_diagnosis_result_relation_columns(conn)
            await self._ensure_sensor_task_columns(conn)
            await self._normalize_legacy_firmware_task_actions(conn)
        self._schema_ready = True

    async def _ensure_diagnosis_result_relation_columns(self, conn) -> None:
        """Add relation columns introduced after the diagnosis_result table existed."""
        columns = [
            "sensor_id",
            "sensor_monitoring_id",
            "device_inst_id",
            "device_spec_id",
            "device_category_id",
        ]
        for column in columns:
            exists = await conn.execute(
                text("SHOW COLUMNS FROM diagnosis_result LIKE :column_name"),
                {"column_name": column},
            )
            if exists.first() is None:
                await conn.execute(
                    text(f"ALTER TABLE diagnosis_result ADD COLUMN {column} CHAR(32) NULL")
                )

            index_name = f"ix_diagnosis_result_{column}"
            index_exists = await conn.execute(
                text("SHOW INDEX FROM diagnosis_result WHERE Key_name = :index_name"),
                {"index_name": index_name},
            )
            if index_exists.first() is None:
                await conn.execute(
                    text(f"CREATE INDEX {index_name} ON diagnosis_result ({column})")
                )

    async def _ensure_sensor_task_columns(self, conn) -> None:
        """Add task metadata columns introduced after sensor_task existed."""
        columns = {
            "remark": "TEXT NULL",
            "dispatched_at": "DATETIME NULL",
        }
        for column, definition in columns.items():
            exists = await conn.execute(
                text("SHOW COLUMNS FROM sensor_task LIKE :column_name"),
                {"column_name": column},
            )
            if exists.first() is None:
                await conn.execute(
                    text(f"ALTER TABLE sensor_task ADD COLUMN {column} {definition}")
                )

    async def _normalize_legacy_firmware_task_actions(self, conn) -> None:
        """Move tasks generated by the old firmware action=2 code to action=0."""
        await conn.execute(
            text(
                "UPDATE sensor_task SET action = 0 "
                "WHERE action = 2 AND name LIKE 'Firmware Upgrade %'"
            )
        )

    async def close(self) -> None:
        """Close database engine"""
        if self.engine:
            await self.engine.dispose()
            self._schema_ready = False
            logger.info("MySQL database closed")

    async def get_session(self) -> AsyncGenerator[AsyncSession, None]:
        """Get database session"""
        if not self.SessionLocal:
            raise RuntimeError("Database not initialized. Call init() first.")
        async with self.SessionLocal() as session:
            try:
                yield session
            except Exception as e:
                await session.rollback()
                logger.error(f"Session error: {e}")
                raise
            finally:
                await session.close()

    async def health_check(self) -> bool:
        """Check MySQL database health"""
        try:
            async with self.SessionLocal() as session:
                await session.execute(text("SELECT 1"))
                return True
        except Exception as e:
            logger.error(f"MySQL health check failed: {e}")
            return False


# ===== Redis Connection =====
class RedisManager:
    """Manager for Redis connections"""

    def __init__(self):
        self.client: Optional[redis.Redis] = None

    def init(self, redis_url: str) -> None:
        """Initialize Redis connection"""
        try:
            self.client = redis.from_url(redis_url, decode_responses=True)
            self.health_check()
            # logger.info("Redis connection initialized successfully")
        except Exception as e:
            logger.error(f"Failed to initialize Redis: {e}")
            raise

    def close(self) -> None:
        """Close Redis connection"""
        if self.client:
            self.client.close()
            logger.info("Redis connection closed")

    def health_check(self) -> bool:
        """Check Redis connection health"""
        try:
            if self.client:
                self.client.ping()
                return True
            return False
        except Exception as e:
            logger.error(f"Redis health check failed: {e}")
            return False

    def get_client(self) -> redis.Redis:
        """Get Redis client"""
        if not self.client:
            raise RuntimeError("Redis not initialized. Call init() first.")
        return self.client


# ===== InfluxDB Connection =====
class InfluxDBManager:
    """Manager for InfluxDB connections"""

    def __init__(self):
        self.client: Optional[InfluxDBClient] = None
        self.org: str = ""
        self.bucket: str = ""

    def init(self, influx_url: str, influx_token: str, influx_org: str, influx_bucket: str = "sentinel-accel-raw-data") -> None:
        """Initialize InfluxDB connection"""
        try:
            self.org = influx_org
            self.bucket = influx_bucket
            self.client = InfluxDBClient(
                url=influx_url,
                token=influx_token,
                org=influx_org,
            )
            self.health_check()
            # logger.info("InfluxDB connection initialized successfully")
        except Exception as e:
            logger.error(f"Failed to initialize InfluxDB: {e}")
            raise

    def close(self) -> None:
        """Close InfluxDB connection"""
        if self.client:
            self.client.close()
            logger.info("InfluxDB connection closed")

    def health_check(self) -> bool:
        """Check InfluxDB connection health"""
        try:
            if self.client:
                self.client.health()
                return True
            return False
        except Exception as e:
            logger.error(f"InfluxDB health check failed: {e}")
            return False

    def get_client(self) -> InfluxDBClient:
        """Get InfluxDB client"""
        if not self.client:
            raise RuntimeError("InfluxDB not initialized. Call init() first.")
        return self.client


# ===== MinIO Connection =====
class MinIOManager:
    """Manager for MinIO connections"""

    def __init__(self):
        self.client: Optional[Minio] = None
        self._bucket: str = ""

    def init(
        self,
        endpoint: str,
        access_key: str,
        secret_key: str,
        secure: bool = False,
        bucket: str = "fft",
    ) -> None:
        """Initialize MinIO connection"""
        try:
            self._bucket = bucket
            self.client = Minio(
                endpoint=endpoint,
                access_key=access_key,
                secret_key=secret_key,
                secure=secure,
            )
            self.health_check()
            self._ensure_bucket()
            # logger.info("MinIO connection initialized successfully")
        except Exception as e:
            logger.error(f"Failed to initialize MinIO: {e}")
            raise

    def close(self) -> None:
        """Close MinIO connection"""
        logger.info("MinIO connection closed")

    def health_check(self) -> bool:
        """Check MinIO connection health"""
        try:
            if self.client:
                self.client.bucket_exists(self._bucket)
                return True
            return False
        except Exception as e:
            logger.error(f"MinIO health check failed: {e}")
            return False

    def _ensure_bucket(self) -> None:
        """Ensure the default bucket exists, create if not"""
        try:
            if self.client:
                if not self.client.bucket_exists(self._bucket):
                    self.client.make_bucket(self._bucket)
                    logger.info(f"Created MinIO bucket: {self._bucket}")
        except S3Error as e:
            logger.error(f"Error managing MinIO bucket: {e}")

    def get_client(self) -> Minio:
        """Get MinIO client"""
        if not self.client:
            raise RuntimeError("MinIO not initialized. Call init() first.")
        return self.client


# Global instances — created once, initialized by each service's startup
db_manager = DatabaseManager()
redis_manager = RedisManager()
influxdb_manager = InfluxDBManager()
minio_manager = MinIOManager()
