// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import UserOutlined from '/Users/tju/Langhu/Products/Sentinel/Codes/Platform/client/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import RadarChartOutlined from '/Users/tju/Langhu/Products/Sentinel/Codes/Platform/client/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RadarChartOutlined';
import ToolOutlined from '/Users/tju/Langhu/Products/Sentinel/Codes/Platform/client/admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ToolOutlined';
export default { UserOutlined, RadarChartOutlined, ToolOutlined };
