// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/tju/Workspace/LH.朗湖科技/Sentinel/Codes/Platform/client/portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import AppstoreOutlined from '/Users/tju/Workspace/LH.朗湖科技/Sentinel/Codes/Platform/client/portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import ClusterOutlined from '/Users/tju/Workspace/LH.朗湖科技/Sentinel/Codes/Platform/client/portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ClusterOutlined';
import RadarChartOutlined from '/Users/tju/Workspace/LH.朗湖科技/Sentinel/Codes/Platform/client/portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RadarChartOutlined';
import TeamOutlined from '/Users/tju/Workspace/LH.朗湖科技/Sentinel/Codes/Platform/client/portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
export default { DashboardOutlined, AppstoreOutlined, ClusterOutlined, RadarChartOutlined, TeamOutlined };
