// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/register","layout":false,"id":"2"},"3":{"path":"/device","name":"设备管理","icon":"AppstoreOutlined","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/device/categories","name":"设备分类","parentId":"3","id":"4"},"5":{"path":"/device/specs","name":"设备规格","parentId":"3","id":"5"},"6":{"path":"/device/list","name":"设备列表","parentId":"3","id":"6"},"7":{"path":"/device","redirect":"/device/categories","parentId":"3","id":"7"},"8":{"path":"/process","name":"生产工艺","icon":"ClusterOutlined","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"/process/templates","name":"工段模板","parentId":"8","id":"9"},"10":{"path":"/process/manage","name":"工段管理","parentId":"8","id":"10"},"11":{"path":"/process","redirect":"/process/templates","parentId":"8","id":"11"},"12":{"path":"/monitoring","name":"监测管理","icon":"RadarChartOutlined","parentId":"ant-design-pro-layout","id":"12"},"13":{"path":"/monitoring/sensors","name":"传感器","parentId":"12","id":"13"},"14":{"path":"/monitoring/points","name":"测点设置","parentId":"12","id":"14"},"15":{"path":"/monitoring","redirect":"/monitoring/sensors","parentId":"12","id":"15"},"16":{"path":"/welcome","name":"Welcome","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"16"},"17":{"path":"/profile","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"17"},"18":{"path":"/change-password","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"18"},"19":{"path":"/","redirect":"/device/categories","parentId":"ant-design-pro-layout","id":"19"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Register__index" */'@/pages/Register/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Device__Category__index" */'@/pages/Device/Category/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Device__Spec__index" */'@/pages/Device/Spec/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Device__List__index" */'@/pages/Device/List/index.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import('./EmptyRoute')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Process__Template__index" */'@/pages/Process/Template/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Process__Manage__index" */'@/pages/Process/Manage/index.tsx')),
'11': React.lazy(() => import('./EmptyRoute')),
'12': React.lazy(() => import('./EmptyRoute')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__Sensors__index" */'@/pages/Monitoring/Sensors/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__Monitoring__Points__index" */'@/pages/Monitoring/Points/index.tsx')),
'15': React.lazy(() => import('./EmptyRoute')),
'16': React.lazy(() => import(/* webpackChunkName: "p__Welcome__index" */'@/pages/Welcome/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__Profile__index" */'@/pages/Profile/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__ChangePassword__index" */'@/pages/ChangePassword/index.tsx')),
'19': React.lazy(() => import('./EmptyRoute')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/tju/Workspace/PDI/Sentinel/Codes/platform/portal/web/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
