// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Provider, useModel } from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/src/.umi/plugin-antd/types.d';
export * from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/src/.umi/plugin-layout/types.d';
export * from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/tju/Workspace/PDI/Sentinel/Codes/platform/admin/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
