# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\xb8\x01\n\x0cMsgRmsReport\x12\n\n\x02sn\x18\x01 \x01(\r\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x0b\n\x03iso\x18\x03 \x01(\r\x12\r\n\x05rms_x\x18\x04 \x01(\x02\x12\r\n\x05rms_y\x18\x05 \x01(\x02\x12\r\n\x05rms_z\x18\x06 \x01(\x02\x12\r\n\x05rms_m\x18\x07 \x01(\x02\x12\x0e\n\x06peak_x\x18\x08 \x01(\x02\x12\x0e\n\x06peak_y\x18\t \x01(\x02\x12\x0e\n\x06peak_z\x18\n \x01(\x02\x12\x0e\n\x06peak_m\x18\x0b \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSGRMSREPORT']._serialized_start=18
  _globals['_MSGRMSREPORT']._serialized_end=202
# @@protoc_insertion_point(module_scope)

# Type alias for Pylance static analysis support
MsgRmsReport = _globals['MsgRmsReport']
