# ==============================================================================
# 1. 全局与代理配置 (Agent)
# ==============================================================================
[agent]
  # 数据批处理大小（重要！针对高频数据，可以在内存中攒够 5000 条再往 InfluxDB 写一次）
  metric_batch_size = 5000
  # 刷新间隔：每 1 秒将内存中的批次刷入数据库
  flush_interval = "1s"
  # 开启调试模式，方便刚开始排查问题（正式上线后可以改成 false）
  debug = true

# ==============================================================================
# 2. 输入插件：接收 ESP32 发来的 HTTP 请求
# ==============================================================================
[[inputs.http_listener_v2]]
  # Telegraf 将在 8080 端口监听。ESP32 会向 http://<服务器IP>:8080/write 发 POST 请求
  service_address = ":7009"
  paths = ["/write"]
  methods = ["POST"]
  
  # 告诉 Telegraf，收到的数据已经是 InfluxDB 的 Line Protocol 格式了，无需解析直接透传
  data_format = "influx"

# ==============================================================================
# 3. 输出插件：将数据写入 InfluxDB v2
# ==============================================================================
[[outputs.influxdb_v2]]
  # InfluxDB 的地址。
  # 【排坑警告】如果 Telegraf 和 InfluxDB 都在 Docker 里，请填宿主机的局域网 IP，或者使用 Docker 网络别名。
  # 如果都在物理机本地，填 http://127.0.0.1:8086
  urls = ["http://influxdb:8086"] 
  
  # 填入第一步获取的三要素
  token = "MuKqZ3VckkTIM3q4Gj_4TYEoYI-OYLRJueKWQPDPOsQZzHnjKHC56GXgrUKd3vZiGhATJ4EnhWsMSuumdVzaCw=="
  organization = "myorg"
  bucket = "sentinel-accel-raw-data"

[[inputs.mqtt_consumer]]
  servers  = ["tcp://139.9.50.7:1883"]
  topics   = ["sentinel"]
  username = "api"
  password = "api@sH123"

  data_format           = "xpath_protobuf"
  xpath_protobuf_files  = ["/etc/telegraf/messages.proto"]
  xpath_protobuf_type   = "MsgRmsReport"

  [[inputs.mqtt_consumer.xpath]]
    metric_name = "'rms_report'"

    [inputs.mqtt_consumer.xpath.tags]
      sn  = "string(sn)"
      iso = "string(iso)"

    [inputs.mqtt_consumer.xpath.fields]
      temperature = "number(temperature)"
      rms_x       = "number(rms_x)"
      rms_y       = "number(rms_y)"
      rms_z       = "number(rms_z)"
      rms_m       = "number(rms_m)"
      peak_x      = "number(peak_x)"
      peak_y      = "number(peak_y)"
      peak_z      = "number(peak_z)"
      peak_m      = "number(peak_m)"
    [inputs.mqtt_consumer.xpath.fields_int]
      sn  = "sn"
      iso = "iso"
