CREATE TABLE diagnosis_notification_delivery (
    id CHAR(32) NOT NULL COMMENT 'UUID primary key',
    event_id CHAR(32) NOT NULL COMMENT 'MQTT event UUID',
    diagnosis_id CHAR(32) NOT NULL COMMENT 'Diagnosis UUID',
    report_id CHAR(32) NULL COMMENT 'DiagnosisRecord UUID snapshot',
    device_id CHAR(32) NOT NULL COMMENT 'DeviceInst UUID',
    sensor_sn VARCHAR(255) NULL COMMENT 'Sensor SN snapshot',
    device_category_id CHAR(32) NULL COMMENT 'Device category UUID snapshot',
    process_device_id CHAR(32) NULL COMMENT 'Process device UUID snapshot',
    overall_level TINYINT UNSIGNED NOT NULL COMMENT '1=关注,2=异常,3=告警,4=严重',
    employee_id CHAR(32) NOT NULL COMMENT 'Employee UUID',
    wx_user_id VARCHAR(255) NOT NULL COMMENT 'Resolved WeChat user id',
    notification_date DATE NOT NULL COMMENT 'Beijing local date',
    diagnosed_at DATETIME(6) NOT NULL COMMENT 'Diagnosis completion time in UTC',
    status TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0=PENDING,1=SENDING,2=SENT,3=FAILED',
    sent_at DATETIME(6) NULL COMMENT 'WeChat send completion time in UTC',
    last_error VARCHAR(1024) NULL COMMENT 'Last send failure reason',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_diagnosis_notification_delivery_daily (
        device_id,
        overall_level,
        employee_id,
        notification_date
    ),
    KEY idx_diagnosis_notification_event (event_id),
    KEY idx_diagnosis_notification_employee_status (employee_id, status),
    KEY idx_diagnosis_notification_date_status (notification_date, status),
    KEY idx_diagnosis_notification_diagnosis (diagnosis_id),
    KEY idx_diagnosis_notification_report (report_id),
    KEY idx_diagnosis_notification_device (device_id),
    KEY idx_diagnosis_notification_sensor_sn (sensor_sn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
